# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Use npm ci to install dependencies without running scripts
RUN npm ci --ignore-scripts

# Copy all project files
COPY . .

# Build the project
RUN npm run build

# Ensure the main file is executable (if not already set)
RUN chmod +x build/index.js

# Set environment variables for Docker (actual values should be provided at runtime)
ENV COTI_MCP_AES_KEY=""
ENV COTI_MCP_PRIVATE_KEY=""
ENV COTI_MCP_PUBLIC_KEY=""
ENV COTI_MCP_NETWORK=""

# Command to run the MCP server
CMD ["node", "build/index.js"]